
---

- name:  run the pmsrvconfig cmd in bath mode
  hosts: all
  gather_facts: true
  become: true
  vars:
    - pwd_pmserver: "XXXXXXXX"
  tasks:
    - shell: |
        /opt/quest/sbin/pmsrvconfig -a --batch -q <<' EOF'
        {{ pwd_pmserver }}
        {{ pwd_pmserver }}
        EOF
