---

- name: Galaxy role oneidentity.privilege_manager.software
  hosts: all
  gather_facts: true
  become: true
  #those variables are reset in the AWX template. Defined for local play.
  vars:

    # Directories
    software_dir: "/home/ansible/.ansible/software/7.3.0.2"

    # Software
    software_pkg_state:
      plugin: present
      server: check
      agent: check

    # Facts
    software_facts_generate: true
    software_facts_verbose: false

    # Reports
    software_reports_generate: true
    software_reports_backup: false
    software_reports_host: "localhost"
    software_reports:
     - src:  software_report.csv.j2
       dest: /tmp/reports/software_report.csv

  roles:
    - name: oneidentity.privilege_manager.software
