---

- name: Galaxy role oneidentity.privilege_manager.join
  hosts: all
  gather_facts: true
  become: true

  # The variables you would most likely want/need to override have been included
  vars:

    # Join
    join_server: 192.168.193.135
    join_state: "unjoined"
    join_password: "njfrbbur6ldM%45"

    # Facts
    join_facts_generate: true
    join_facts_verbose: true

    # Reports
    join_reports_generate: true
    join_reports_backup: false

  roles:
    - name: oneidentity.privilege_manager.join
