---

- name: "Galaxy role oneidentity.privilege_manager.sudo_policy_for_unix_host"
  hosts: all
  gather_facts: false
  become: true

  # The variables you would most likely want/need to override have been included
  vars:
    # Reports
    sudo_policy_for_unix_host_reports_generate: true
    sudo_policy_for_unix_host_reports_backup: false
    sudo_policy_for_unix_host_reports_host: "localhost"  
    sudo_policy_for_unix_host_reports:
      - src:  sudo_policy_for_unix_host_report.csv.j2
        dest: /tmp/reports/sudo_policy_for_unix_host_report.csv


  roles:
    - name: oneidentity.privilege_manager.sudo_policy_for_unix_host
