---

- name: Galaxy role oneidentity.privilege_manager.software
  hosts: all
  gather_facts: true
  become: true
  #those variables are reset in the AWX template. Defined for local play.
  vars:

    # Directories
    software_dir: "/root/Ansible_work/sources/6.1.1.0"

    # Software
    software_pkg_state:
      plugin: present
      server: check
      agent: check

    # Facts
    software_facts_generate: true
    software_facts_verbose: false

    # Reports
    software_reports_generate: true
    software_reports_backup: false

  roles:
    - name: oneidentity.privilege_manager.software
