---

- name: Galaxy role oneidentity.privilege_manager.join
  hosts: all
  gather_facts: true
  become: true

  # The variables you would most likely want/need to override have been included
  vars:

    # Join
    join_server: 10.0.0.9
    join_state: "joined"
    join_password: "Password1!"

    # Facts
    join_facts_generate: true
    join_facts_verbose: true

    # Reports
    join_reports_generate: true
    join_reports_backup: false
    join_reports_host: "localhost"
    join_reports:
      - src:  join_report.csv.j2
        dest: /tmp/reports/join_report.csv

  roles:
    - name: oneidentity.privilege_manager.join
