---
- name: copy packages
  hosts: all
  become: true

  tasks:
  - name: copy affective
    ansible.builtin.copy:
      src: "client/linux-x86_64/vasclnt-5.0.3-39941.x86_64.rpm"
      dest: /root
      owner: root
      group: root
      mode: u=rw,g=rw,o=r
